const BUILD_VERSION='v.0.26.05.23.0831';
const SAVE_KEY='purpleHouse_'+BUILD_VERSION;
const WORLD_W=1672, WORLD_H=941;
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');
const promptEl=document.getElementById('prompt'),modal=document.getElementById('modal'),modalCard=document.getElementById('modalCard');
let W=900,H=650,keys={},near=null,frame=0,sceneScale=1,sceneX=0,sceneY=0;
const bg=new Image();
bg.src='the_purple_witch_s_village_hub.png';
const baseRel=()=>({trust:0,fear:0,debt:0,gratitude:0,resentment:0,suspicion:0});
const state={version:BUILD_VERSION,day:1,time:'Morning',coins:12,familiar:null,inventory:{Sunmint:2,Thornroot:1,'Grave Soil':1},stats:{Kindness:0,Power:0,Balance:0,Greed:0,Mischief:0},upgrades:{Shop:false,Attic:false,Greenhouse:false,Basement:false},servedToday:false,questIndex:0,graveRisk:0,ghostFavor:0,ghostDebt:0,prepaidGraves:0,relationships:{},pendingFollowUps:[],storyArchive:[],divinationUsedToday:false,revealedQuest:null,exploredToday:false,discoveredPlaces:{House:true,Gardens:true,Graveyard:true}};
const witch={x:720,y:630,vx:0,vy:0,dir:1}; const logs=[];
const quests=[
 {id:'mara_baker',name:'Mara the Baker',ask:'Mara wants a potion that will make everyone love her bread.',truth:'Her oven was hexed by jealousy, but she is tempted by shortcut magic.',choices:{good:{text:'Brew a Hearth-Mending Tonic and fix the oven.',need:['Sunmint','Lantern Moss'],stat:'Kindness',coin:6,rel:{trust:2,gratitude:2},follow:'Mara leaves a warm loaf on your step. The village says your magic made honest work bloom again.'},evil:{text:'Enchant the village into craving her bread.',need:['Whisper Mold','Nightshade Bells'],stat:'Power',coin:11,rel:{fear:2,suspicion:1},follow:'Half the village queued for bread at midnight. Mara is rich, but people are starting to worry about their own thoughts.'},gray:{text:'Sell her a one-week popularity charm with a clearly worded contract.',need:['Dewberries'],stat:'Balance',coin:9,rel:{debt:1,trust:1},follow:'Mara paid on time and kept the charm modest. She now owes you a favor and a basket of rolls.'},mischief:{text:'Make the bread sing compliments until people buy it.',need:['Moon Chamomile'],stat:'Mischief',coin:7,rel:{trust:1,suspicion:1},follow:'The singing bread is unbearable, but the children love it. The mayor has banned tenor sourdough after sunset.'}}},
 {id:'old_bram',name:'Old Bram',ask:'Bram asks you to curse the foxes stealing from his henhouse.',truth:'The foxes are feeding kits in the graveyard wall.',choices:{good:{text:'Ward the henhouse without harming the foxes.',need:['Sunmint'],stat:'Kindness',coin:6,rel:{trust:2,gratitude:1},follow:'Bram grudgingly admits the foxes stopped coming. Tiny pawprints now circle the graveyard offerings instead.'},evil:{text:'Mark the foxes with a fear hex.',need:['Thornroot','Grave Soil'],stat:'Power',coin:10,rel:{fear:1,resentment:1},follow:'No foxes approach Bram now. No birds sing near his farm either.'},gray:{text:'Trade a fox-proof charm for fresh eggs each week.',need:['Lantern Moss'],stat:'Balance',coin:8,rel:{debt:2},follow:'Bram delivered eggs and complained the whole time. He still came back to ask about goat wards.'},mischief:{text:'Teach the hens to chase foxes in tiny helmets.',need:['Whisper Mold'],stat:'Mischief',coin:7,rel:{trust:1,suspicion:1},follow:'The hens won. Bram is terrified of them now, but the foxes are deeply impressed.'}}},
 {id:'lina_tailor',name:'Lina the Tailor',ask:'Lina wants a rival to forget the design she copied.',truth:'Both tailors stole from the same ghost’s burial gown.',choices:{good:{text:'Return the pattern to the ghost and inspire new work.',need:['Bone Dust','Sunmint'],stat:'Kindness',coin:6,rel:{trust:2,gratitude:2},ghost:1,follow:'The graveyard felt lighter after the pattern was returned. Lina has started sewing mourning ribbons for free.'},evil:{text:'Bottle the rival’s memory and sell it back later.',need:['Spirit Thread','Widowcap'],stat:'Power',coin:12,rel:{fear:2,suspicion:2},ghost:-1,follow:'A woman wept outside the tailor shop, unable to remember why fabric made her sad. The ghosts noticed.'},gray:{text:'Erase only the stolen detail and collect a favor.',need:['Spirit Thread'],stat:'Balance',coin:9,rel:{debt:1,trust:1},follow:'Both tailors changed their patterns. Neither admits you helped, which means both can be charged later.'},mischief:{text:'Make every copied dress sprout judgmental sleeves.',need:['Nightshade Bells'],stat:'Mischief',coin:7,rel:{suspicion:2},follow:'The dresses point accusingly at plagiarists. Business is down, but morality in fashion is up.'}}},
 {id:'mayor_puddlewick',name:'Mayor Puddlewick',ask:'The mayor wants your help making the town less afraid of your shop.',truth:'He also wants to control which villagers may visit you.',choices:{good:{text:'Host a free remedy day.',need:['Dewberries','Sunmint'],stat:'Kindness',coin:4,rel:{trust:2,gratitude:1},follow:'The free remedy day softened the town. Puddlewick smiled like it was his idea.'},evil:{text:'Make him publicly praise you with silver-tongue magic.',need:['Whisper Mold','Moon Chamomile'],stat:'Power',coin:10,rel:{fear:2,resentment:2},follow:'The mayor praised you until his jaw ached. The town laughed, then looked toward your house very carefully.'},gray:{text:'Accept his proposal but keep a secret back door for desperate villagers.',need:['Lantern Moss'],stat:'Balance',coin:8,rel:{debt:1,suspicion:1},follow:'Respectable villagers use the front door now. Desperate ones knock at the back after moonrise.'},mischief:{text:'Paint the moon purple for one night.',need:['Moon Chamomile','Ghostcap'],stat:'Mischief',coin:6,rel:{suspicion:2,trust:1},follow:'Nobody feared your shop while the moon was purple. They were too busy arguing whether it matched your roof.'}}},
 {id:'tessa_widow',name:'Tessa the Widow',ask:'Tessa asks to speak with her husband’s ghost one last time.',truth:'Her husband already left a message, but another ghost has been pretending to be him.',choices:{good:{text:'Use a clean spirit rite and reveal the true message.',need:['Spirit Thread','Sunmint'],stat:'Kindness',coin:5,rel:{trust:2,gratitude:3},ghost:1,follow:'Tessa left a candle at the cemetery gate and thanked you without words. The right ghost finally moved on.'},evil:{text:'Bind the false ghost and sell its secrets.',need:['Bone Dust','Thornroot'],stat:'Power',coin:12,rel:{fear:2,suspicion:1},ghost:-1,follow:'The false ghost is quiet now. Too quiet. Your spirit ledger feels colder.'},gray:{text:'Let her speak briefly, but charge the ghost a debt for lying.',need:['Grave Soil'],stat:'Balance',coin:9,rel:{debt:1,trust:1},ghost:1,follow:'Tessa got goodbye. The lying ghost now owes you three whispers and a moonlit favor.'},mischief:{text:'Make the impostor confess in Tessa’s husband’s terrible singing voice.',need:['Ghostcap'],stat:'Mischief',coin:6,rel:{trust:1,suspicion:1},follow:'Tessa laughed and cried. The graveyard hummed off-key until dawn.'}}},
 {id:'nib_goatherd',name:'Nib the Goat-Herder',ask:'Nib wants his neighbor’s moon cabbages to stop biting his goats.',truth:'The goats started the feud by eating enchanted seedlings.',choices:{good:{text:'Brew a harmless goat-repelling garden wash.',need:['Lantern Moss'],stat:'Kindness',coin:6,rel:{trust:2},follow:'The goats avoid the cabbages now, though one still glares at the moon.'},evil:{text:'Curse the cabbages to bite only Nib.',need:['Thornroot','Widowcap'],stat:'Power',coin:11,rel:{fear:2,resentment:1},follow:'Nib learned respect for vegetables. The vegetables learned ambition.'},gray:{text:'Charge both sides for a boundary charm.',need:['Dewberries','Grave Soil'],stat:'Balance',coin:10,rel:{debt:2},follow:'A glowing line now separates goats from cabbages. Both neighbors complain equally, which feels fair.'},mischief:{text:'Give the goats tiny manners and the cabbages tiny insults.',need:['Moon Chamomile'],stat:'Mischief',coin:7,rel:{suspicion:2},follow:'The dispute is now conducted entirely through polite bleats and rude leaves.'}}},
 {id:'orin_clerk',name:'Orin the Clerk',ask:'Orin wants help finding out who keeps moving his inkpot.',truth:'A child ghost is practicing handwriting at night.',choices:{good:{text:'Leave pencils and ask the ghost what it wants to write.',need:['Spirit Thread'],stat:'Kindness',coin:5,rel:{trust:2,gratitude:1},ghost:1,follow:'The child ghost wrote thank-you notes on every window in town. Orin is frightened but organized.'},evil:{text:'Trap the ghost in the inkpot.',need:['Bone Dust','Nightshade Bells'],stat:'Power',coin:11,rel:{fear:2},ghost:-1,follow:'Orin’s ink never spills now. It also watches him.'},gray:{text:'Make a bargain: the ghost may write after office hours.',need:['Grave Soil'],stat:'Balance',coin:8,rel:{debt:1,trust:1},ghost:1,follow:'Official records are tidier. Unofficial records include several ghost poems about taxes.'},mischief:{text:'Enchant the inkpot to flee from boring paperwork only.',need:['Whisper Mold'],stat:'Mischief',coin:6,rel:{suspicion:2},follow:'The inkpot refuses dull forms. Town bureaucracy has never been more dramatic.'}}},
 {id:'pippa_child',name:'Pippa from the Lane',ask:'Pippa wants a charm so the other children stop calling her unlucky.',truth:'She is not unlucky; she keeps noticing problems before adults do.',choices:{good:{text:'Give her a confidence charm and teach her omen-sense.',need:['Sunmint','Moon Chamomile'],stat:'Kindness',coin:3,rel:{trust:3,gratitude:2},follow:'Pippa warned the baker before a shelf fell. The children now call her Weather Eye, which she likes.'},evil:{text:'Make every child who mocks her hiccup frogs.',need:['Thornroot','Whisper Mold'],stat:'Power',coin:8,rel:{fear:2,suspicion:1},follow:'Nobody teases Pippa now. Several parents have questions about amphibians.'},gray:{text:'Sell a small luck charm and ask for one honest warning later.',need:['Dewberries'],stat:'Balance',coin:5,rel:{debt:1,trust:2},follow:'Pippa paid with a button and a warning: the mayor keeps a list of names who visit you.'},mischief:{text:'Make bad luck follow anyone who says the word unlucky.',need:['Nightshade Bells'],stat:'Mischief',coin:5,rel:{trust:1,suspicion:2},follow:'The village has invented six new words for unlucky. None are safe.'}}}
];

const fams=[
  {name:'Black Cat',bonus:'Detects lies and softens suspicious villagers.',color:'#16151d'},
  {name:'Raven',bonus:'Finds secrets, omens, and graveyard clues.',color:'#111827'},
  {name:'Toad',bonus:'Improves brewing and occasionally saves ingredients.',color:'#5f9b62'},
  {name:'Bat',bonus:'Helps with night gathering and ghosts.',color:'#3b2b4f'},
  {name:'Fox',bonus:'Unlocks clever mischief and gray solutions.',color:'#c06a36'}
];
const spots=[
  {id:'house',x:1020,y:520,r:150,label:'Purple House',hint:'Open the shop, brew, scry, upgrade, or sleep'},
  {id:'familiar',x:720,y:655,r:80,label:'Familiar Nook',hint:'Choose or visit your familiar'},
  {id:'helpGarden',x:1285,y:320,r:100,label:'Helpful Garden',hint:'Gather kind and protective herbs'},
  {id:'poisonGarden',x:1310,y:525,r:100,label:'Poisonous Garden',hint:'Gather dangerous ingredients'},
  {id:'graveyard',x:1310,y:775,r:115,label:'Spirit Graveyard',hint:'Gather eerie ingredients or leave offerings'},
  {id:'paths',x:285,y:645,r:100,label:'Village Signpost',hint:'Explore the Town Square or Whispering Woods'},
  {id:'well',x:485,y:368,r:62,label:'Old Well',hint:'Peer into the well for rumors and lost things'}
];
const locationLabels=[
  {name:'Helpful Garden',x:1365,y:272},
  {name:'Poisonous Garden',x:1380,y:485},
  {name:'Spirit Offering',x:1275,y:720},
  {name:'Town Square',x:245,y:560},
  {name:'Whispering Woods',x:210,y:670}
];

function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function log(t){logs.unshift(t);logs.splice(12);state.storyArchive.unshift({day:state.day,text:t});state.storyArchive.splice(100);renderSide();}
function resize(){const box=document.getElementById('gameBox').getBoundingClientRect();canvas.width=Math.floor(box.width*devicePixelRatio);canvas.height=Math.floor(box.height*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=box.width;H=box.height;updateSceneMetrics();} window.addEventListener('resize',resize);
function updateSceneMetrics(){sceneScale=Math.min(W/WORLD_W,H/WORLD_H);sceneX=(W-WORLD_W*sceneScale)/2;sceneY=(H-WORLD_H*sceneScale)/2;}
function sx(x){return sceneX+x*sceneScale} function sy(y){return sceneY+y*sceneScale} function sw(v){return v*sceneScale} function cs(){return sceneScale}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill(); if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(1.5,2*cs());ctx.stroke();}}
function drawBackground(){
  if(bg.complete && bg.naturalWidth){ctx.drawImage(bg,sceneX,sceneY,WORLD_W*sceneScale,WORLD_H*sceneScale);}
  else{let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#4a2e5e');g.addColorStop(.5,'#2a2036');g.addColorStop(1,'#161018');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
  ctx.fillStyle='rgba(8,5,14,.18)'; ctx.fillRect(0,0,W,H);
  const glow=ctx.createRadialGradient(sx(1030),sy(520),10,sx(1030),sy(520),sw(330)); glow.addColorStop(0,'rgba(255,220,160,.08)'); glow.addColorStop(1,'rgba(0,0,0,0)'); ctx.fillStyle=glow; ctx.fillRect(0,0,W,H);
}
function drawSpotMarker(sp,active){ctx.save();const pulse=(Math.sin(frame*.08)+1)/2;ctx.globalAlpha=active?.92:.48;ctx.beginPath();ctx.arc(sx(sp.x),sy(sp.y),sw(active?sp.r*.42:sp.r*.26)+pulse*sw(4),0,Math.PI*2);ctx.fillStyle=active?'rgba(255,223,174,.15)':'rgba(198,151,228,.10)';ctx.fill();ctx.strokeStyle=active?'rgba(255,223,174,.92)':'rgba(198,151,228,.42)';ctx.lineWidth=Math.max(1.5,2.2*cs());ctx.stroke();ctx.restore();}
function drawLocationLabels(){ctx.save();ctx.font=`${Math.max(11,14*cs())}px Georgia`;ctx.textAlign='center';locationLabels.forEach(l=>{const tw=ctx.measureText(l.name).width+18;roundRect(sx(l.x)-tw/2,sy(l.y)-sw(16),tw,sw(24),sw(12),'rgba(35,24,39,.82)','rgba(217,180,101,.5)');ctx.fillStyle='#f5dfae';ctx.fillText(l.name,sx(l.x),sy(l.y));});ctx.restore();}
function drawFamiliar(){if(!state.familiar)return; const bob=Math.sin(frame*.18+1.4)*sw(4); const fx=sx(witch.x-38*witch.dir), fy=sy(witch.y+16)+bob; ctx.save(); ctx.fillStyle='rgba(0,0,0,.25)'; ctx.beginPath(); ctx.ellipse(fx,fy+sw(18),sw(18),sw(8),0,0,Math.PI*2); ctx.fill(); ctx.fillStyle=state.familiar.color||'#111'; ctx.beginPath(); ctx.ellipse(fx,fy,sw(16),sw(12),0,0,Math.PI*2); ctx.fill(); ctx.beginPath(); ctx.moveTo(fx-sw(10),fy-sw(6)); ctx.lineTo(fx-sw(4),fy-sw(18)); ctx.lineTo(fx,fy-sw(7)); ctx.closePath(); ctx.fill(); ctx.beginPath(); ctx.moveTo(fx+sw(2),fy-sw(7)); ctx.lineTo(fx+sw(9),fy-sw(18)); ctx.lineTo(fx+sw(12),fy-sw(6)); ctx.closePath(); ctx.fill(); ctx.fillStyle='#f5dfae'; ctx.beginPath(); ctx.arc(fx-sw(5),fy-sw(1),sw(1.8),0,Math.PI*2); ctx.arc(fx+sw(5),fy-sw(1),sw(1.8),0,Math.PI*2); ctx.fill(); ctx.restore();}
function drawWitch(){const bob=Math.sin(frame*.18)*sw(7); const x=sx(witch.x), y=sy(witch.y)+bob; ctx.save(); ctx.fillStyle='rgba(0,0,0,.28)'; ctx.beginPath(); ctx.ellipse(x,y+sw(26),sw(23),sw(10),0,0,Math.PI*2); ctx.fill(); ctx.translate(x,y); if(witch.dir<0)ctx.scale(-1,1); ctx.fillStyle='#6b3f8a'; ctx.beginPath(); ctx.moveTo(-sw(9),-sw(20)); ctx.lineTo(sw(16),-sw(14)); ctx.lineTo(sw(2),-sw(42)); ctx.closePath(); ctx.fill(); ctx.fillStyle='#8a60b7'; ctx.fillRect(-sw(12),-sw(12),sw(24),sw(30)); ctx.fillStyle='#f2d0b0'; ctx.beginPath(); ctx.arc(0,-sw(16),sw(9),0,Math.PI*2); ctx.fill(); ctx.fillStyle='#55306e'; ctx.beginPath(); ctx.ellipse(0,-sw(26),sw(18),sw(5),0,0,Math.PI*2); ctx.fill(); ctx.beginPath(); ctx.moveTo(-sw(8),-sw(26)); ctx.lineTo(sw(15),-sw(26)); ctx.lineTo(sw(2),-sw(48)); ctx.closePath(); ctx.fill(); ctx.fillStyle='#d9b465'; ctx.fillRect(sw(2),-sw(32),sw(7),sw(4)); ctx.restore();}
function drawWorld(){ctx.clearRect(0,0,W,H); drawBackground(); drawLocationLabels(); spots.forEach(sp=>drawSpotMarker(sp,near && near.id===sp.id)); drawFamiliar(); drawWitch(); if(near){ctx.save();ctx.font=`700 ${Math.max(12,15*cs())}px Georgia`;const text=near.label;const tw=ctx.measureText(text).width+20;roundRect(sx(near.x)-tw/2,sy(near.y)-sw(near.r*.65)-sw(34),tw,sw(28),sw(12),'rgba(35,24,39,.84)','rgba(217,180,101,.55)');ctx.fillStyle='#fff3d0';ctx.textAlign='center';ctx.fillText(text,sx(near.x),sy(near.y)-sw(near.r*.65)-sw(16));ctx.restore();}}
function closeModal(){modal.style.display='none';}
function show(title,html){modalCard.innerHTML=`<h2>${title}</h2>${html}<button class="secondary" onclick="closeModal()">Close</button>`; modal.style.display='flex';}
function addInv(name,n=1){state.inventory[name]=(state.inventory[name]||0)+n;log(`Gathered ${n} ${name}.`); renderSide();}
function consume(list){for(const k of list){if((state.inventory[k]||0)<=0)return false;} list.forEach(k=>state.inventory[k]--); return true;}
function hasAll(list){return list.every(k=>(state.inventory[k]||0)>0);}
function relFor(id){if(!state.relationships[id])state.relationships[id]=baseRel();return state.relationships[id];}
function addRel(id,changes){const r=relFor(id); Object.entries(changes||{}).forEach(([k,v])=>r[k]=(r[k]||0)+v);}
function relHTML(id){const r=relFor(id); return `<div class="rel">${Object.entries(r).map(([k,v])=>`<div><b>${k}</b><br>${v}</div>`).join('')}</div>`;}
function update(){frame++; let ax=0,ay=0; if(keys.ArrowLeft||keys.a)ax--; if(keys.ArrowRight||keys.d)ax++; if(keys.ArrowUp||keys.w)ay--; if(keys.ArrowDown||keys.s)ay++; let len=Math.hypot(ax,ay)||1; witch.vx+=(ax/len)*1.0; witch.vy+=(ay/len)*1.0; witch.vx*=.80; witch.vy*=.80; witch.x=Math.max(70,Math.min(WORLD_W-70,witch.x+witch.vx)); witch.y=Math.max(140,Math.min(WORLD_H-75,witch.y+witch.vy)); if(Math.abs(witch.vx)>.1)witch.dir=witch.vx>0?1:-1; near=null; let best=1e9; for(const sp of spots){let d=Math.hypot(witch.x-sp.x,witch.y-sp.y); if(d<sp.r && d<best){best=d; near=sp;}} if(near){promptEl.style.display='block'; promptEl.textContent=`E: ${near.label} — ${near.hint}`;} else promptEl.style.display='none'; drawWorld(); requestAnimationFrame(update);}
function interact(){if(!near)return; const id=near.id; if(id==='house')houseMenu(); if(id==='familiar')familiarMenu(); if(id==='helpGarden')helpGardenGather(); if(id==='poisonGarden')poisonGardenGather(); if(id==='graveyard')graveyardMenu(); if(id==='paths')exploreMenu(); if(id==='well')wellMenu(); renderSide();}
function helpGardenGather(){const items=['Sunmint','Lantern Moss','Dewberries','Moon Chamomile']; addInv(items[Math.floor(Math.random()*items.length)],state.upgrades.Greenhouse?2:1); state.time='Afternoon';}
function poisonGardenGather(){const items=['Thornroot','Nightshade Bells','Widowcap','Whisper Mold']; addInv(items[Math.floor(Math.random()*items.length)]); state.stats.Power+=1; state.time='Afternoon';}
function houseMenu(){show('The Purple House',`<p>The crooked purple house now appears as an isometric village hub while keeping the same systems underneath it. Use the house to run the core of your witch life.</p><div class="choices"><button class="good" onclick="questMenu()">Open Shop / Serve Today's Visitor</button><button onclick="brewMenu()">Brew at the Cauldron</button><button class="secondary" onclick="atticMenu()">Use the Attic Divination Mirror</button><button class="secondary" onclick="upgradeMenu()">House Upgrades</button><button class="secondary" onclick="endDay()">Go to Bed / End Day</button></div>`);}
function graveyardMenu(){show('Spirit Graveyard',`<p>The fenced graveyard behind the house is both ingredient source and sacred place.</p><div class="choices"><button onclick="graveyardGather()">Gather Graveyard Ingredients</button><button class="secondary" onclick="offeringMenu()">Use the Spirit Offering Plate</button></div><p class="small">Prepayments make gathering safer. Ghost favor may return gifts; ghost debt may cause overnight trouble.</p>`);}
function graveyardGather(){const items=['Grave Soil','Bone Dust','Ghostcap','Spirit Thread']; addInv(items[Math.floor(Math.random()*items.length)]); let prepaid=state.prepaidGraves>0; if(prepaid){state.prepaidGraves--; state.ghostFavor++; log('Your prepaid offering glows. The graveyard allows the taking.'); if(Math.random()<.45)addInv(items[Math.floor(Math.random()*items.length)]);} else {state.graveRisk++; if(Math.random()<.35+state.graveRisk*.06){state.ghostDebt++; log('A ghost noticed you taking things. The Spirit Ledger records a debt.');}} state.time='Evening'; closeModal(); renderSide();}
function offeringMenu(){show('Spirit Offering Plate',`<p>The stone altar hums softly beneath violet candles.</p><p><b>Favor:</b> ${state.ghostFavor} · <b>Debt:</b> ${state.ghostDebt} · <b>Prepaid gatherings:</b> ${state.prepaidGraves}</p><div class="choices"><button onclick="offerCoin()">Leave 3 coins as an offering</button><button onclick="offerIngredient('Bone Dust')">Offer Bone Dust</button><button onclick="offerIngredient('Grave Soil')">Offer Grave Soil</button><button class="secondary" onclick="prepayGrave()">Prepay your next graveyard gathering — 2 coins</button></div>`);}
function offerCoin(){if(state.coins<3){alert('Not enough coins.');return;} state.coins-=3; if(state.ghostDebt>0){state.ghostDebt--; log('The coins vanish. One ghost debt is forgiven.');} else {state.ghostFavor++; log('A pale hand accepts the coins. Ghost favor increases.');} closeModal(); renderSide();}
function offerIngredient(item){if((state.inventory[item]||0)<1){alert('You do not have '+item+'.');return;} state.inventory[item]--; if(state.ghostDebt>0){state.ghostDebt--; state.ghostFavor++; log(`The ${item} crumbles into blue light. A debt is paid, and gratitude lingers.`);} else {state.ghostFavor+=2; log(`The ghosts prize ${item}. Favor rises sharply.`);} closeModal(); renderSide();}
function prepayGrave(){if(state.coins<2){alert('Not enough coins.');return;} state.coins-=2; state.prepaidGraves++; log('You prepay the graveyard. The next gathering will be safer.'); closeModal(); renderSide();}
function divinationOmen(q){
  const fam=state.familiar?state.familiar.name:null;
  let pieces=[]; pieces.push('The mirror shows: '+q.truth);
  const hasGhost=Object.values(q.choices).some(c=>c.ghost);
  if(fam==='Raven')pieces.push('Raven omen: the choice with the cleanest future is rarely the choice that pays best.');
  if(fam==='Black Cat')pieces.push('Cat sense: listen for the part of the request they avoid saying twice.');
  if(fam==='Bat'&&hasGhost)pieces.push('Bat sense: there is spirit-business tangled in this request. The graveyard will remember.');
  if(fam==='Fox')pieces.push('Fox grin: a gray bargain could leave someone owing you later.');
  if(fam==='Toad')pieces.push('Toad croak: check your ingredients before promising miracles.');
  pieces.push('Possible echoes: kindness may build trust; dark magic may build fear; gray magic may create debt; mischief may create suspicious laughter.');
  return pieces.join(' ');
}
function atticMenu(){
  if(!state.upgrades.Attic){show('Locked Attic',`<p>The attic window glows faintly, but the stair door is still sealed.</p><p>Unlock the <b>Attic</b> from House Upgrades to use divination.</p>`);return;}
  const q=quests[state.questIndex%quests.length];
  if(state.servedToday){show('Attic Divination Mirror',`<p>The mirror is quiet. Today's visitor has already left.</p><p class="small">Use divination before making a request choice to reveal hidden motives and possible consequences.</p>`);return;}
  if(state.divinationUsedToday){let txt=state.revealedQuest&&state.revealedQuest.day===state.day?state.revealedQuest.text:'The mirror has already spent today's vision.';show('Attic Divination Mirror',`<p>${esc(txt)}</p><p class="small">The mirror will clear tomorrow morning.</p>`);return;}
  show('Attic Divination Mirror',`<p>A silver-purple mirror hangs beneath the crooked roof. It can reveal one hidden truth about today's visitor.</p><p><b>Current visitor:</b> ${q.name}</p><div class="choices"><button onclick="useDivination()">Scry today's request</button></div><p class="small">Raven, Cat, Bat, Fox, and Toad familiars add different hints.</p>`);
}
function useDivination(){if(!state.upgrades.Attic||state.divinationUsedToday)return; const q=quests[state.questIndex%quests.length]; const text=divinationOmen(q); state.divinationUsedToday=true; state.revealedQuest={id:q.id,day:state.day,text}; state.stats.Balance+=1; log(`Attic vision: ${q.name}'s request has a hidden truth. The mirror whispers enough to make you cautious.`); closeModal(); show('Attic Vision Revealed',`<p>${esc(text)}</p><p class="small">This clue will also appear on the visitor request screen today.</p>`); renderSide();}
function familiarMenu(){show('Choose Your Familiar',`<p>Your familiar follows with the same cheerful bounce as the witch and gives a small passive bonus.</p><div class="choices">${fams.map(f=>`<button onclick='state.familiar=${JSON.stringify(f)};log("${f.name} chose you as much as you chose them.");closeModal();renderSide();'>${f.name}<br><span class="small">${f.bonus}</span></button>`).join('')}</div>`);}
function brewMenu(){show('Cauldron',`<p>The cauldron burbles. Brew simple potions from ingredients you gather.</p><div class="choices"><button class="good" onclick="brew('Kind Remedy',['Sunmint','Lantern Moss'],'Kindness')">Kind Remedy — Sunmint + Lantern Moss</button><button class="bad" onclick="brew('Minor Hex',['Thornroot','Grave Soil'],'Power')">Minor Hex — Thornroot + Grave Soil</button><button onclick="brew('Balanced Charm',['Dewberries','Spirit Thread'],'Balance')">Balanced Charm — Dewberries + Spirit Thread</button><button onclick="brew('Trickster Tonic',['Whisper Mold','Moon Chamomile'],'Mischief')">Trickster Tonic — Whisper Mold + Moon Chamomile</button></div><p class="small">Potions still work like the previous build while the visuals move closer to the original purple-house inspiration.</p>`);}
function brew(name,ings,stat){if(consume(ings)){state.inventory[name]=(state.inventory[name]||0)+1; state.stats[stat]+=2; state.coins+=2; log(`Brewed ${name}. The shop smells like ${stat.toLowerCase()}.`); closeModal();} else alert('Missing ingredients: '+ings.join(' + ')); renderSide();}
function questMenu(){if(state.servedToday){show('Potion Shop',`<p>You already handled today’s visitor. End the day to invite tomorrow’s trouble.</p>`);return;} let q=quests[state.questIndex%quests.length]; let rel=relHTML(q.id); let reveal=(state.revealedQuest&&state.revealedQuest.day===state.day&&state.revealedQuest.id===q.id)?`<div class="notice"><b>Attic Vision:</b> ${esc(state.revealedQuest.text)}</div>`:`<p class="small">Unlock/use the Attic Divination Mirror to reveal hidden truths before choosing.</p>`; let html=`<p><b>${q.ask}</b></p>${reveal}<h2>Village Memory: ${q.name}</h2>${rel}<div class="choices">`; for(const [type,c] of Object.entries(q.choices)){ let cls=type==='good'?'good':type==='evil'?'bad':type==='mischief'?'secondary':''; let label={good:'Good Witch',evil:'Dark Witch',gray:'Gray Witch',mischief:'Mischief Witch'}[type]; let ok=hasAll(c.need); html+=`<button class="${cls}" ${ok?'':'disabled'} onclick="resolveQuest('${type}')">${label}: ${c.text}<br><span class="small">Requires: ${c.need.join(' + ')}${ok?'':' — missing ingredients'}</span></button>`; } html+=`</div><p class="small">Named villager memory, follow-up rumors, ghost standing, and attic divination are all preserved in this build.</p>`; show(q.name,html);}
function resolveQuest(type){let q=quests[state.questIndex%quests.length],c=q.choices[type]; if(!consume(c.need)){alert('Missing ingredients: '+c.need.join(' + ')); return;} state.servedToday=true; state.questIndex++; state.time='Night'; state.stats[c.stat]+=3; if(type==='gray')state.stats.Greed+=1; state.coins+=c.coin; addRel(q.id,c.rel); if(c.ghost){if(c.ghost>0)state.ghostFavor+=c.ghost; else state.ghostDebt+=Math.abs(c.ghost);} state.pendingFollowUps.push({day:state.day+1,text:c.follow,id:q.id,type}); log(`${q.name} left. ${type==='good'?'You gave them what they needed.':type==='evil'?'You gave them power with a price.':type==='gray'?'A tidy bargain was recorded.':'The solution will be talked about for days.'}`); closeModal(); renderSide();}
function upgradeMenu(){const opts=[['Shop',18,'More shelves, more customers, and a warmer shopfront.'],['Attic',22,'Unlocks a once-per-day Divination Mirror that reveals hidden truths.'],['Greenhouse',25,'Improves helpful garden yields and rare herbs.'],['Basement',30,'Forbidden rituals, bottled secrets, and dangerous choices.']]; show('House Customization & Unlocks',`<p>The purple house is now presented as a stylized isometric hub. Future versions can push further into a full village exploration map and eventually a broader isometric world.</p><div class="choices">${opts.map(o=>`<button onclick="buyUpgrade('${o[0]}',${o[1]})">${state.upgrades[o[0]]?'✓ ':''}${o[0]} — ${o[1]} coins<br><span class="small">${o[2]}</span></button>`).join('')}</div>`);}
function buyUpgrade(name,cost){if(state.upgrades[name]){alert('Already unlocked.');return;} if(state.coins<cost){alert('Not enough coins.');return;} state.coins-=cost; state.upgrades[name]=true; log(`Unlocked the ${name}. The purple house creaked happily.`); closeModal(); renderSide();}
function exploreMenu(){if(state.exploredToday){show('Village Signpost',`<p>You already took your exploration trip today.</p><p class="small">Return tomorrow to push farther into the village and the woods. This is the first roadmap step toward an eventually explorable full village map.</p>`);return;} show('Village Signpost',`<p>The new village-hub update opens the first true exploration step in the roadmap. For now, you can make one trip a day.</p><div class="choices"><button onclick="explore('Town Square')">Visit Town Square</button><button onclick="explore('Whispering Woods')">Walk to Whispering Woods</button><button onclick="explore('Lantern Lane')">Stroll Lantern Lane</button></div>`);}
function explore(where){let text=''; state.exploredToday=true; state.discoveredPlaces[where]=true; if(where==='Town Square'){ const roll=Math.random(); if(roll<.34){state.coins+=3; text='You sold a quick charm at the Town Square fountain and earned 3 coins.';} else if(roll<.67){state.stats.Trust=(state.stats.Trust||0); addInv('Dewberries'); text='You overheard rumors in Town Square and came home with Dewberries and a better feel for the village mood.';} else {let q=quests[state.questIndex%quests.length]; text=`In Town Square, gossip circles around ${q.name}. You suspect they may visit soon.`;} state.time='Afternoon'; }
  else if(where==='Whispering Woods'){ const woods=['Moon Chamomile','Whisper Mold','Lantern Moss','Ghostcap']; addInv(woods[Math.floor(Math.random()*woods.length)]); if(Math.random()<.35){state.ghostFavor++; text='The woods were quiet but full of murmurs. You returned with a rare ingredient and a slight increase in ghost favor.';} else {text='You explored the Whispering Woods and came home with a rare ingredient tucked under your cloak.';} state.stats.Mischief+=1; state.time='Evening'; }
  else if(where==='Lantern Lane'){ state.coins+=2; state.stats.Balance+=1; text='A walk down Lantern Lane put you in villagers’ path. You picked up 2 coins in errands and learned a little more about the town.'; state.time='Afternoon'; }
  log(text); closeModal(); renderSide();}
function wellMenu(){show('Old Well',`<p>The old well reflects the house and the moon strangely.</p><div class="choices"><button onclick="wellWish()">Drop in a coin and make a wish</button><button class="secondary" onclick="wellPeer()">Peer into the well for a rumor</button></div>`);}
function wellWish(){if(state.coins<1){alert('Not enough coins.');return;} state.coins-=1; if(Math.random()<.5){state.ghostFavor++; log('The well swallowed your coin and answered with a kind ripple. Ghost favor rises.');} else {addInv('Spirit Thread'); log('A coin sank into the well and a strand of Spirit Thread floated up.');} closeModal(); renderSide();}
function wellPeer(){const q=quests[state.questIndex%quests.length]; log(`The water briefly shows ${q.name} standing outside your shop, practicing what to say.`); state.stats.Balance+=1; closeModal(); renderSide();}
function endDay(){let top=Object.entries(state.stats).sort((a,b)=>b[1]-a[1])[0]||['mystery',0]; state.day++; state.time='Morning'; state.servedToday=false; state.divinationUsedToday=false; state.revealedQuest=null; state.graveRisk=Math.max(0,state.graveRisk-1); state.exploredToday=false; state.inventory.Sunmint=(state.inventory.Sunmint||0)+1; state.inventory.Thornroot=(state.inventory.Thornroot||0)+1; let due=state.pendingFollowUps.filter(f=>f.day<=state.day); state.pendingFollowUps=state.pendingFollowUps.filter(f=>f.day>state.day); if(due.length){due.forEach(f=>{log('Rumor: '+f.text); if(f.type==='evil')state.stats.Power++; if(f.type==='good')state.stats.Kindness++; if(f.type==='mischief')state.stats.Mischief++; if(f.type==='gray')state.stats.Balance++;});} else log(`Day ${state.day} begins. The village whispers most about your ${top[0].toLowerCase()}.`); if(state.ghostDebt>0 && Math.random()<0.35){state.coins=Math.max(0,state.coins-state.ghostDebt); log('Unpaid ghost debt rattled the cupboards. Some coins went missing overnight.');} if(state.ghostFavor>0 && Math.random()<0.3){addInv(['Bone Dust','Spirit Thread','Ghostcap'][Math.floor(Math.random()*3)]); state.ghostFavor--; log('A grateful ghost left a useful ingredient by the plate.');} saveGame(false); renderSide();}
function villageNotesMenu(){let rows=Object.entries(state.relationships); let rels=rows.length?rows.map(([id,r])=>{let q=quests.find(x=>x.id===id); return `<h2>${q?q.name:id}</h2><div class="rel">${Object.entries(r).map(([k,v])=>`<div><b>${k}</b><br>${v}</div>`).join('')}</div>`;}).join(''):'<p>No villager has a history with you yet.</p>'; let archive=state.storyArchive.slice(0,28).map(e=>`<div>Day ${e.day}: ${esc(e.text)}</div>`).join(''); show('Village Notes & Story Ledger',`<p>Relationship memory is active. Story entries will eventually connect to cutscenes, and the rumor board/story log will eventually become larger or expandable. This build also adds the first step toward a more explorable village map.</p>${rels}<h2>Recent Story Entries</h2><div id="notes">${archive||'<div>No entries yet.</div>'}</div>`);}
function showRumors(){show('Rumor Board',`<p>The current rumor board is still compact, but future builds can make it larger or expandable.</p><div id="notes">${(logs.length?logs:['Arrive at the crooked purple house. The village is already whispering.']).map(l=>`<div>${esc(l)}</div>`).join('')}</div>`);}
function showTendencies(){show('Witch Tendencies',`<div class="statgrid">${Object.entries(state.stats).map(([k,v])=>`<div class="stat"><b>${k}</b>: ${v}<div class="bar"><div class="fill" style="width:${Math.min(100,(v/Math.max(5,...Object.values(state.stats)))*100)}%"></div></div></div>`).join('')}</div>`);}
function renderSide(){document.getElementById('versionPill').textContent=BUILD_VERSION; document.getElementById('dayPill').textContent='Day '+state.day; document.getElementById('timePill').textContent=state.time; document.getElementById('coinPill').textContent='Coins '+state.coins; document.getElementById('famBox').innerHTML=state.familiar?`<b>${state.familiar.name}</b><br>${state.familiar.bonus}`:'Choose one at the Familiar Nook.'; document.getElementById('invWorld').innerHTML=Object.entries(state.inventory).filter(([k,v])=>v>0).map(([k,v])=>`<span class="tag">${esc(k)} ×${v}</span>`).join('')||'<span class="small">Empty</span>'; let max=Math.max(5,...Object.values(state.stats)); document.getElementById('stats').innerHTML=Object.entries(state.stats).map(([k,v])=>`<div class="stat"><b>${k}</b>: ${v}<div class="bar"><div class="fill" style="width:${Math.min(100,v/max*100)}%"></div></div></div>`).join(''); document.getElementById('upgrades').innerHTML=Object.entries(state.upgrades).map(([k,v])=>`${v?'✓':'○'} ${k}`).join('<br>'); document.getElementById('spiritBox').innerHTML=`Favor ${state.ghostFavor||0} · Debt ${state.ghostDebt||0} · Prepaid ${state.prepaidGraves||0}`; const places=Object.keys(state.discoveredPlaces).join(', '); document.getElementById('mapBox').innerHTML=`Exploration trip today: <b>${state.exploredToday?'Used':'Available'}</b><br>Discovered places: ${places}<br><span class="small">Use the Village Signpost to start exploring the wider village. This is the next roadmap step and the first move toward a future full map.</span>`; document.getElementById('log').innerHTML=logs.map(l=>`<div>${esc(l)}</div>`).join('')||'<div>Arrive at the crooked purple house. The village is already whispering.</div>';}
function saveGame(manual=true){try{localStorage.setItem(SAVE_KEY,JSON.stringify({state,logs})); localStorage.setItem('purpleHouse_latest_key',SAVE_KEY); if(manual)log('Game saved.');}catch(e){if(manual)alert('Save failed: '+e.message);}}
function mergeState(src){if(!src)return; Object.assign(state,src); state.version=BUILD_VERSION; state.inventory=Object.assign({Sunmint:0,Thornroot:0},state.inventory||{}); state.stats=Object.assign({Kindness:0,Power:0,Balance:0,Greed:0,Mischief:0},state.stats||{}); state.upgrades=Object.assign({Shop:false,Attic:false,Greenhouse:false,Basement:false},state.upgrades||{}); state.relationships=state.relationships||{}; state.pendingFollowUps=state.pendingFollowUps||[]; state.storyArchive=state.storyArchive||[]; state.ghostFavor=state.ghostFavor||0; state.ghostDebt=state.ghostDebt||0; state.prepaidGraves=state.prepaidGraves||0; state.divinationUsedToday=!!state.divinationUsedToday; state.revealedQuest=state.revealedQuest||null; state.exploredToday=!!state.exploredToday; state.discoveredPlaces=Object.assign({House:true,Gardens:true,Graveyard:true},state.discoveredPlaces||{});}
function loadGame(manual=false){try{let key=localStorage.getItem('purpleHouse_latest_key')||SAVE_KEY; let raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem(key)||localStorage.getItem('purpleHouse_v0_4')||localStorage.getItem('purpleHouse_v0_3'); if(!raw){if(manual)alert('No save found.'); return false;} let data=JSON.parse(raw); mergeState(data.state); logs.length=0; (data.logs||[]).slice(0,12).forEach(x=>logs.push(x)); if(manual)log('Game loaded into '+BUILD_VERSION+'.'); renderSide(); return true;}catch(e){if(manual)alert('Load failed: '+e.message); return false;}}
window.addEventListener('keydown',e=>{keys[e.key]=true; if(e.key.toLowerCase()==='e')interact(); if(e.key==='Escape')closeModal();});
window.addEventListener('keyup',e=>keys[e.key]=false);
document.getElementById('actBtn').onclick=interact;
document.querySelectorAll('[data-dir]').forEach(b=>{let d=b.dataset.dir;b.onpointerdown=()=>{keys[{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[d]]=true}; b.onpointerup=b.onpointerleave=()=>{keys[{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[d]]=false};});
resize();
if(!loadGame(false)){log('You inherited the purple house at the end of town. Tonight, the village finally starts opening up beyond your front path.');}
renderSide();
update();
